@myToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVhOTI4Y2UzNDJjMDUwNDc4NzRhMDUyIn0sImlhdCI6MTU4ODY3MjYzMCwiZXhwIjoxNTg5MDMyNjMwfQ.DKI-QYQbnHPru7sZex9ZMTaJAyf1u_nm71Gyon-rM-s
@RubyToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVhOTMwZTFlMzFkMzExMjQ0MTM3OTgzIn0sImlhdCI6MTU4ODQxMDA5MywiZXhwIjoxNTg4NzcwMDkzfQ.3xIwRV0DNbEESPwRNSWOBWQPNGxagt3M8ub8oe8fKMw
@UboyToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVhOTYzNzk4ZTY4NzgxMDhjYmZkNWI0In0sImlhdCI6MTU4ODE1OTM1MywiZXhwIjoxNTg4NTE5MzUzfQ.Gwqf9OsdniWoeTGzxYJ278iF0pobD3U1PCzG-hdJlWQ
@baseURL = http://localhost:5000/api
@contentType = application/json

//root route
GET http://localhost:5000/

###
//USER ROUTE
//create User
POST {{baseURL}}/users/
content-type: {{contentType}}

{
    "name": "Monty",
    "email": "montytan2000@gmail.com",
    "password": "123456"
}

###
//create Ruby User
POST {{baseURL}}/users/
content-type: {{contentType}}

{
    "name": "Ruby",
    "email": "rubygetsetgo@gmail.com",
    "password": "123456"
}

###
//create Uboy User
POST {{baseURL}}/users/
content-type: {{contentType}}

{
    "name": "Uboy",
    "email": "uboygotan@gmail.com",
    "password": "123456"
}

###
//get auth user
GET {{baseURL}}/auth/
x-auth-token: {{myToken}}

###
//Login Monty user
Post {{baseURL}}/auth/
content-type: {{contentType}}

{
    "email": "montytan2000@gmail.com",
    "password": "123456"
}

###
//Login Ruby user
Post {{baseURL}}/auth/
content-type: {{contentType}}

{
    "email": "rubygetsetgo@gmail.com",
    "password": "123456"
}

###
//Login Uboy user
Post {{baseURL}}/auth/
content-type: {{contentType}}

{
    "email": "uboygotan@gmail.com",
    "password": "123456"
}

###
//PROFILE ROUTE
//get all profile
GET {{baseURL}}/profile/

###

//get all profile
GET {{baseURL}}/profile/user/5ea928ce342c05047874a052

###
//create profile
POST {{baseURL}}/profile/me/new
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "status": "Finally Employed",
    "website": "https://github.com/tanmontgomeryf",
    "skills": "HTML, CSS, JS",
    "location": "Manila, Ph",
    "bio": "Dad of 2!",
    "githubusername": "tanmontgomeryf",
    "social": {
        "facebook": "https://www.facebook.com/montytan2000"
    }
}

###
//create Ruby profile
POST {{baseURL}}/profile/me/new
content-type: {{contentType}}
x-auth-token: {{RubyToken}}

{
    "company": "SM Supermalls",
    "status": "Employed",
    "skills": "Design, Best Mom,",
    "location": "Manila, Ph",
    "bio": "Future Mom of 2!",
    "social": {
        "facebook": "https://www.facebook.com/ubaygo",
        "instagram": "https://www.instagram.com/ubaygoes/"
    }
}

###
//create Uboy profile
POST {{baseURL}}/profile/me/new
content-type: {{contentType}}
x-auth-token: {{UboyToken}}

{
    "status": "Baby",
    "skills": "Dance, Sign, Eat Oreo",
    "location": "Manila, Ph",
    "bio": "Lemme see!"
}

###

//get logged in user profile
GET {{baseURL}}/profile/me
x-auth-token: {{myToken}}

###

//get logged in user profile
GET {{baseURL}}/profile/me
x-auth-token: {{RubyToken}}


###
//update my profile
PUT {{baseURL}}/profile/me
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "status": "Still Unemployed",
    "website": "https://github.com/tanmontgomeryf",
    "skills": "HTML, CSS, JS, React",
    "location": "Manila, Ph",
    "bio": "Dad of 2!",
    "githubusername": "tanmontgomeryf",
    "social": {
        "facebook": "https://www.facebook.com/montytan2000",
        "instagram": "https://www.instagram.com/_montytan/"
    }
}

###
//update Ruby profile
PUT {{baseURL}}/profile/me
content-type: {{contentType}}
x-auth-token: {{RubyToken}}

{
    "company": "SM Supermalls",
    "status": "Employed",
    "skills": "Design, Best Mom,",
    "location": "Manila, Ph",
    "bio": "Future Mom of 2!",
    "social": {
        "facebook": "https://www.facebook.com/ubaygo",
        "instagram": "https://www.instagram.com/ubaygoes/"
    }
}

###
//Delete Uboy profile & user
DELETE {{baseURL}}/profile/me
x-auth-token: {{UboyToken}}

###
//Ruby profile create new experience
PUT {{baseURL}}/profile/experience/new
content-type: {{contentType}}
x-auth-token: {{RubyToken}}

{
    "title": "Visual Display Office",
    "company": "SM Supermalls",
    "location": "Valenzuela City, Ph",
    "from": "2-1-2017",
    "current": true,
    "description": "Plans and deploys displays in the mall"
}

###
//Monty profile create new experience
PUT {{baseURL}}/profile/experience/new
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "title": "Marketing Officer",
    "company": "InvestKo PH",
    "location": "Ortigas, Ph",
    "from": "3-12-2019",
    "to": "12-10-2019",
    "description": "Creates, plan, and executes marketing plan to further the image, sales of the brand"
}

###
//Monty profile update experience
PUT {{baseURL}}/profile/experience/5eabf66679c371097c6004f2
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "title": "Editor",
    "company": "ABL",
    "location": "Valenzuela City, Ph",
    "from": "1-20-2019",
    "to": "3-10-2019",
    "description": "GOAT"
}

###
//Delete Monty experience
DELETE {{baseURL}}/profile/experience/5ea96d0400496d045410a241
content-type: {{contentType}}
x-auth-token: {{myToken}}

###
//create new Monty education
PUT {{baseURL}}/profile/education/new
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "school": "University of Santo Tomas",
    "degree": "Bachelors Degree",
    "fieldofstudy": "Advertising Arts",
    "from": "6-10-2009",
    "to": "3-10-2014",
    "description": "Got a bachelors degree in fine arts major in advertising"
}

###
//create new Monty education
PUT {{baseURL}}/profile/education/new
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "school": "Diliman Preparatory School",
    "degree": "Elementary and Highschool",
    "fieldofstudy": "General Studies",
    "from": "6-10-1999",
    "to": "3-15-2009",
    "description": "highschool and elementary"
}

###
//update Monty education
PUT {{baseURL}}/profile/education/5eaaa8666f705913884d964f
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "school": "University of Santo Tomas",
    "degree": "Bachelors Degree",
    "fieldofstudy": "Fine arts major in advertising",
    "from": "6-10-2009",
    "to": "3-10-2014",
    "description": "Got a bachelors degree in fine arts major in advertising"
}

###
//Delete Monty education
DELETE {{baseURL}}/profile/education/5eaaa7096f705913884d964e
content-type: {{contentType}}
x-auth-token: {{myToken}}

###
//Get Github repos
Get {{baseURL}}/profile/github/bradtraversy

###
//add Posts
POST {{baseURL}}/posts
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "text": "I love uboy the most!!"
}

###
//add Posts
POST {{baseURL}}/posts
content-type: {{contentType}}
x-auth-token: {{RubyToken}}

{
    "text": "I love uboy more!!"
}

###
//GET all Posts
GET {{baseURL}}/posts
x-auth-token: {{myToken}}

###
//GET all Posts
GET {{baseURL}}/posts
x-auth-token: {{RubyToken}}

###
//GET Post by ID
GET {{baseURL}}/posts/5eaaf06cbc1930171c140498
x-auth-token: {{myToken}}

###
//Delete Post by ID
DELETE {{baseURL}}/posts/5eabfe6e7f78af1710f6bdd9
x-auth-token: {{myToken}}

###
//Delete Post by ID
DELETE {{baseURL}}/posts/5eabec4b48cda50d34ea4f28
x-auth-token: {{RubyToken}}

###
//Update Post by ID
PUT {{baseURL}}/posts/5eaaf3cabc1930171c140499
content-type: {{contentType}}
x-auth-token: {{RubyToken}}

{
    "text": "I love anime!!"
}

###
//like Post of Ruby as User: Monty
PUT {{baseURL}}/posts/5eabfe6e7f78af1710f6bdd9/like
x-auth-token: {{myToken}}

###
//like Post of Ruby as User: Monty
PUT {{baseURL}}/posts/5eabfe747f78af1710f6bdda/unlike
x-auth-token: {{myToken}}

###
//add comment to a post
POST {{baseURL}}/posts/5ead3c60150923082cb24054/comment
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "text": "don't edit"
}

###
//add comment to a post
POST {{baseURL}}/posts/5ead3c60150923082cb24054/comment
content-type: {{contentType}}
x-auth-token: {{RubyToken}}

{
    "text": "great post dude"
}

###
//delete comment to a post
DELETE {{baseURL}}/posts/5eabfe6e7f78af1710f6bdd9/comment/5ead36c26365040e0865a3d9
x-auth-token: {{myToken}}

###
//delete comment to a post
DELETE {{baseURL}}/posts/5eabfe6e7f78af1710f6bdd9/comment/5ead37966365040e0865a3dd
x-auth-token: {{RubyToken}}

###
//edit a comment
PUT {{baseURL}}/posts/5ead3c60150923082cb24054/comment/5ead3c7c150923082cb24056
content-type: {{contentType}}
x-auth-token: {{RubyToken}}

{
    "text": "great post bhe"
}

###
//edit a comment
PUT {{baseURL}}/posts/5ead3c60150923082cb24054/comment/5ead3c73150923082cb24055
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "text": "joke edit me please!!!!!!$$$"
}