@myToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVhOTI4Y2UzNDJjMDUwNDc4NzRhMDUyIn0sImlhdCI6MTU4ODE0NjM1MywiZXhwIjoxNTg4NTA2MzUzfQ.W6Xn-Bc3N6kuiqZ8dvH6WfgGSCS7Q7985KEeVShDZEs
@RubyToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVhOTMwZTFlMzFkMzExMjQ0MTM3OTgzIn0sImlhdCI6MTU4ODE1NjEzMiwiZXhwIjoxNTg4NTE2MTMyfQ.fLQBCdjdRKMSdPuOejcyCsaK4bMDm2U_OAFyZsCIJ8E
@UboyToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVhOTYzNzk4ZTY4NzgxMDhjYmZkNWI0In0sImlhdCI6MTU4ODE1OTM1MywiZXhwIjoxNTg4NTE5MzUzfQ.Gwqf9OsdniWoeTGzxYJ278iF0pobD3U1PCzG-hdJlWQ
@baseURL = http://localhost:5000/api
@contentType = application/json

//root route
GET http://localhost:5000/

###
//USER ROUTE
//create User
POST {{baseURL}}/users/
content-type: {{contentType}}

{
    "name": "Monty",
    "email": "montytan2000@gmail.com",
    "password": "123456"
}

###
//create Ruby User
POST {{baseURL}}/users/
content-type: {{contentType}}

{
    "name": "Ruby",
    "email": "rubygetsetgo@gmail.com",
    "password": "123456"
}

###
//create Uboy User
POST {{baseURL}}/users/
content-type: {{contentType}}

{
    "name": "Uboy",
    "email": "uboygotan@gmail.com",
    "password": "123456"
}

###
//get auth user
GET {{baseURL}}/auth/
x-auth-token: {{myToken}}

###
//Login Monty user
Post {{baseURL}}/auth/
content-type: {{contentType}}

{
    "email": "montytan2000@gmail.com",
    "password": "123456"
}

###
//Login Ruby user
Post {{baseURL}}/auth/
content-type: {{contentType}}

{
    "email": "rubygetsetgo@gmail.com",
    "password": "123456"
}

###
//Login Uboy user
Post {{baseURL}}/auth/
content-type: {{contentType}}

{
    "email": "uboygotan@gmail.com",
    "password": "123456"
}

###
//PROFILE ROUTE
//get all profile
GET {{baseURL}}/profile/

###

//get all profile
GET {{baseURL}}/profile/user/5ea928ce342c05047874a052

###
//create profile
POST {{baseURL}}/profile/new
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "status": "Finally Employed",
    "website": "https://github.com/tanmontgomeryf",
    "skills": "HTML, CSS, JS",
    "location": "Manila, Ph",
    "bio": "Dad of 2!",
    "githubusername": "tanmontgomeryf",
    "social": {
        "facebook": "https://www.facebook.com/montytan2000"
    }
}

###
//create Ruby profile
POST {{baseURL}}/profile/new
content-type: {{contentType}}
x-auth-token: {{RubyToken}}

{
    "company": "SM Supermalls",
    "status": "Employed",
    "skills": "Design, Best Mom,",
    "location": "Manila, Ph",
    "bio": "Future Mom of 2!",
    "social": {
        "facebook": "https://www.facebook.com/ubaygo",
        "instagram": "https://www.instagram.com/ubaygoes/"
    }
}

###
//create Uboy profile
POST {{baseURL}}/profile/new
content-type: {{contentType}}
x-auth-token: {{UboyToken}}

{
    "status": "Baby",
    "skills": "Dance, Sign, Eat Oreo",
    "location": "Manila, Ph",
    "bio": "Lemme see!"
}

###

//get logged in user profile
GET {{baseURL}}/profile/me
x-auth-token: {{myToken}}


###
//update my profile
PUT {{baseURL}}/profile/me
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "status": "Still Unemployed",
    "website": "https://github.com/tanmontgomeryf",
    "skills": "HTML, CSS, JS, React",
    "location": "Manila, Ph",
    "bio": "Dad of 2!",
    "githubusername": "tanmontgomeryf",
    "social": {
        "facebook": "https://www.facebook.com/montytan2000",
        "instagram": "https://www.instagram.com/_montytan/"
    }
}

###
//update Ruby profile
PUT {{baseURL}}/profile/me
content-type: {{contentType}}
x-auth-token: {{RubyToken}}

{
    "company": "SM Supermalls",
    "status": "Employed",
    "skills": "Design, Best Mom,",
    "location": "Manila, Ph",
    "bio": "Future Mom of 2!",
    "social": {
        "facebook": "https://www.facebook.com/ubaygo",
        "instagram": "https://www.instagram.com/ubaygoes/"
    }
}

###
//Delete Uboy profile & user
DELETE {{baseURL}}/profile/me
x-auth-token: {{UboyToken}}

###
//Ruby profile create new experience
PUT {{baseURL}}/profile/experience/new
content-type: {{contentType}}
x-auth-token: {{RubyToken}}

{
    "title": "Visual Display Office",
    "company": "SM Supermalls",
    "location": "Valenzuela City, Ph",
    "from": "2-1-2017",
    "current": true,
    "description": "Plans and deploys displays in the mall"
}

###
//Monty profile create new experience
PUT {{baseURL}}/profile/experience/new
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "title": "Marketing Officer",
    "company": "InvestKo PH",
    "location": "Ortigas, Ph",
    "from": "3-12-2019",
    "to": "12-10-2019",
    "description": "Creates, plan, and executes marketing plan to further the image, sales of the brand"
}

###
//Monty profile update experience
PUT {{baseURL}}/profile/experience/5ea9a8d01455111c307885b5
content-type: {{contentType}}
x-auth-token: {{myToken}}

{
    "title": "CEO",
    "company": "ABL",
    "location": "Valenzuela City, Ph",
    "from": "1-20-2019",
    "to": "3-10-2019",
    "description": "GOAT"
}

###
//Delete Monty experience
DELETE {{baseURL}}/profile/experience/5ea96d0400496d045410a241
content-type: {{contentType}}
x-auth-token: {{myToken}}

###
//Posts
GET {{baseURL}}/posts/

